var d = new Date();
var days = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
var months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
var week = days[d.getDay()];
var day = d.getDate();
var month = d.getMonth();
var year = d.getFullYear()
var date = week+' '+day+' '+months[month]+' '+year; 
document.getElementById("current-date").innerHTML = date
